### PR TITLE
Refactor: convert to markdown 

### PR DESCRIPTION
**Pull request by marcoscaceres**
* fix a bunch of markup issues
* fix a bunch of xrefs
* define interfaces using new school IDL 
* modernize examples
* small edits

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@igrigorik, there still a few issues with the spec that I was not able to fix - like the `PerformanceServerTiming` interface is not actually defined in the spec? 

Anyway, this should be enough to get things going a bit better.  I fixed a bunch of cross linking issues, but not all... I'll leave those to you as I ran out of time :) The spec helped greatly improve markdown parsing in ReSpec, so that's a good thing.

**Comment by marcoscaceres** [comment]
You can view the spec working here: https://rawgit.com/WICG/server-timing/3cba4f21dec054961fba498678b9765a7372e225/index.html

**Comment by igrigorik** [comment]
@marcoscaceres you sir, are awesome. Thanks for the refresh! Overall, LGTM, modulo few nitpicks..

- `1\*DIGIT [ "." 1\*DIGIT ]` -- extra escape characters in the output.
- Lots of unresolved warnings, but we can fix those later.. we need to do some cleanup; I don't think we need to do it here.

As an aside, could you add me to the repo? Can't merge :-)

**Comment by marcoscaceres** [comment]
@igrigorik done. Apologies for that - seems we forgot to add you as admin when this got transferred over or set up.

**Comment by igrigorik** [comment]
Thanks Marcos!

**Pull request merged**
